var fab = require("./lib/fab")
  , app = require('./lib/app')

with(fab)
(fab)
  (listen, +process.env.PORT || 0xFAB)
  (route, /^\/p\/?$/)
    (app.redirect_to, "/")
  ()
  (route, /^\/create/)
    (app.mock, 'create')
  ()
  ('Hi')
()