var fab = require("./lib/fab")
  , app = require('./lib/app')

with(fab)
(fab)
  (listen, +process.env.PORT || 0xFAB)
  (route, /^\/talks/)
    (require('./lib/app-talks'))
  ()
  (route, /^\/create/)
    (app.mock, 'create')
  ()
  ('Hi')
()